### ISSUE TITLE
Strange effect when saving files

### ISSUE THREAD

**Issue by mwarkentin** [bdkjones/CodeKit-1-Old#240]
Hi there.. just installed Codekit, and added my scss file.

My page looks ok after refreshing: ![Before save](http://f.cl.ly/items/2W2y0d2A3h2d2y043u1l/Come%20Together%20-%20Event%20Videos%20Online.jpg)

But after saving the scss file, my browser automatically updates, and all links become bold and have the url show up: ![After save](http://f.cl.ly/items/3K0K0H130a1H3r433U0P/Come%20Together%20-%20Event%20Videos%20Online.png)

Any idea what could be causing this?

**Comment by bdkjones** [comment]
Huh. That's weird. 

Can you send me the project that's demonstrating this issue so that I can test over here?

**Comment by WolfieZero** [comment]
I've had a similar issue where the style would change when CodeKit refresh the page to something I hadn't changed (my width went from 100% to 70%). It turns out that because I had two style-sheets on a page (one screen and the other print). So the browser would understand what one to process but CodeKit would just process all the files it self had processed in the order it did it in.

Hope that helps suss out the issue.

**Comment by bdkjones** [comment]
Yep, that's gonna be the issue. The fix is going to be to stop CodeKit from injecting the styles from any print stylesheets. I'll see what I can do. 

In the meantime, simply making sure that your print.css tag in the HEAD element is the FIRST stylesheet that you reference should resolve the issue. (The later styles in other sheets will override the earlier ones from the print stylesheet.)

**Comment by mwarkentin** [comment]
Ok, I'll give that a shot.. thanks.

**Comment by mwarkentin** [comment]
Hmm.. I loaded `print.css` first, and it improved a bit (font sizes are staying the same), but I'm still seeing the link url being displayed afterwards:

![After moving print to the top](http://f.cl.ly/items/0m1O1C1m2n3h3W03233M/ColorSnapper-3.png)

This is what my css block looks like (I'm editing base.css):

``` html
<link rel="stylesheet" href="{{ STATIC_URL }}css/blueprint/print.css" type="text/css" media="print" />
<link rel="stylesheet" href="{{ STATIC_URL }}css/blueprint/screen.css" type="text/css" media="screen, projection" />
<!--[if IE]>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/blueprint/ie.css" type="text/css" media="screen, projection" />
<![endif]-->
<link rel="stylesheet" href="{{ STATIC_URL }}css/base.css" type="text/css" />
```

**Comment by mwarkentin** [comment]
Unchecking "When possible, inject changes without a full reload" fixes this for me for now.

**Comment by bdkjones** [comment]
Okay, not only have I fixed this issue, I've completely rewritten the live reloading code to be far more efficient. PLUS, it now even works for file:// urls!

It'll be in the next beta, but if you'd like to test an interim build for me, please send me an email and I'll get that out to you before the next public beta goes live in a couple weeks.

**Comment by mwarkentin** [comment]
Thanks for the fast turn around here!

I'd be happy to test it out.. but I'm not sure where to find your email.
