### ISSUE TITLE
Less error "undefined" for Twitter Bootstrap

### ISSUE THREAD

**Issue by richstandbrook** [bdkjones/CodeKit-1-Old#50]
This is very off the cuff feedback. I get it to compile Twitters Bootstrap less files. The log just says "undefined". I don't know if this is unique to Bootstrap but I can't see any problems with the less (it does compile fine with LessApp ;p)

**Comment by richstandbrook** [comment]
Had a little time to follow this up and it seems to be this line in forms.less https://github.com/twitter/bootstrap/blob/master/lib/forms.less#L31. Still not sure exactly _why_. Perhaps the version of Less compiler? If I remove that line it compiles ok. Less app compiles it with or without that line, otherwise I would raise an issue with Twitter Bootstrap.

**Comment by paulyoung** [comment]
It's because the class has the the same name as the mixin.

See here https://github.com/bdkjones/CodeKit/issues/44

**Comment by richstandbrook** [comment]
But why does Less.app compile it fine then?  @paulyoung the related issue is not that helpful as the links are broken so there is no context for the comments.

**Comment by paulyoung** [comment]
Less.app works because it uses an older version of Less.

I cleaned up my Dropbox so that's why the links were broken. They should be working now.

**Comment by richstandbrook** [comment]
So is the issue with Twitter Bootstrap?

**Comment by paulyoung** [comment]
The issue is with the version of less being used in CodeKit.

As a workaround try changing

```
form .clearfix {
```

to

```
form *.clearfix {
```

**Comment by bdkjones** [comment]
I'm using Twitter Bootstrap (albeit a heavily customized version) as the backbone of the new CodeKit website and I have not run into this issue.

Additionally, keep in mind that the ONLY file in all of Twitter's Bootstrap framework that is meant to be compiled is "bootstrap.less" ALL the other files are only meant to be imported into bootstrap.less. 

So if you're trying to compile forms.less into forms.css, you're doing it wrong.

Issue closed.

**Comment by richstandbrook** [comment]
I still get this undefined error, I am using a fresh install of bootstrap as a framework importing bootstrap.less only.

**Comment by richstandbrook** [comment]
This relates to this issue for Twitter Bootstrap https://github.com/twitter/bootstrap/issues/238. They seem to be saying its a problem with a specific version of less?

**Comment by bdkjones** [comment]
I have discussed this issue with Alexis and he just patched Less to fix the bug. 

I've updated CodeKit and can confirm that it now compiles Twitter's Bootstrap framework correctly. Note, however, that I'm not sure the element in question is going to bring in the .clearfix() mixin --- Alexis said that it should not pick up that mixin at all.
